TRUNCATE TABLE stage.customer_research RESTART IDENTITY CASCADE;
TRUNCATE TABLE stage.user_activity_log RESTART IDENTITY CASCADE;
TRUNCATE TABLE stage.user_order_log RESTART IDENTITY CASCADE;
TRUNCATE TABLE mart.d_calendar RESTART IDENTITY CASCADE;
TRUNCATE TABLE mart.d_city RESTART IDENTITY CASCADE;
TRUNCATE TABLE mart.d_customer RESTART IDENTITY CASCADE;
TRUNCATE TABLE mart.d_item RESTART IDENTITY CASCADE;
TRUNCATE TABLE mart.f_activity RESTART IDENTITY CASCADE;
TRUNCATE TABLE mart.f_daily_sales RESTART IDENTITY CASCADE;
TRUNCATE TABLE mart.f_research RESTART IDENTITY CASCADE;
TRUNCATE TABLE mart.f_customer_retention RESTART IDENTITY CASCADE;

ALTER TABLE stage.user_order_log ADD COLUMN status varchar NULL;
ALTER TABLE stage.customer_research ADD COLUMN status varchar NULL;
ALTER TABLE stage.user_activity_log ADD COLUMN status varchar NULL;

